### ISSUE TITLE
Figma Link

### ISSUE THREAD

**Issue by audreystolze** [gxc-challenge-winter21/gxc-team-4#64]
Dear Team #recyclers

As we started to work on your grading we find under sprint 2 a nice description and the great video you produced, but it is missing the basic: a link to your Figma prototype. On the sprint 1 wii page there is a link, however this is returning an error. 
Could one of you asap please add the correct Figma link for prototype 1 and add one prototype 2?

Thanks a lot in advance. Best wishes for the holidays.

Regards,
Audrey

**Comment by eeissfeldt** [comment]
Dear @audreystolze,

I am very sorry about these problems, I have added the link for sprint two and updated the link of sprint one. There has been a QR code for the Sprint two Prototype in our readme, but it was not labeled clear enough.

Best Regards,
Emanuel

**Comment by audreystolze** [comment]
Thanks. Both links work now.

Best Regards
Audrey
